spring:
  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false

  output:
    ansi:
      enabled: always

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    vertex:
      ai:
        gemini:
          project-id: ${GOOGLE_API_KEY}
          location: asia-northeast3
          chat:
            options:
              model: "vertex--pro-vision"

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          github:
            client-name: GitHub
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/github
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
        provider:
          github:
            user-info-uri: https://api.github.com/user


mailgun:
  api-key: ${MAILGUN_API_KEY}
  domain: ${MAILGUN_DOMAIN}
  from: ${MAILGUN_FROM}

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.backend: DEBUG

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

custom:
  jwt:
    access-token:
      expire-time: "#{24 * 60 * 60 * 1000}"
    refresh-token:
      expire-time: "#{72 * 60 * 60 * 1000}"
    secretPattern: ${SECRET_PATTERN}

openai:
  url: ${OPENAI_API_URL}
  admin:
    api-key: ${OPENAI_ADMIN_API_KEY}
    url: ${OPENAI_ADMIN_API_URL}

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}


toss:
  payments:
    base-url: "https://api.tosspayments.com"
    secret-key: ${PAYMENT_SECRET_KEY}

resilience4j:
  circuitbreaker:
    configs:
      aiExternal:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 10s
    circuitbreakerAspectOrder: -3
  retry:
    configs:
      aiRetry:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponential-backoff-multiplier: 2.0
    retryAspectOrder: -4
  ratelimiter:
    configs:
      rateLimiterAI:
        limitForPeriod: 1
        limitRefreshPeriod: 10s
        timeoutDuration: 0
    instances:
      rateLimiterAI:
        baseConfig: rateLimiterAI
    ratelimiterAspectOrder: -2